add rna samples, gtf and refflat
biopet/biowdl-test-utils pull request #7
Opened 2018-06-21 13:44 UTC by DavyCats

### Description

_Give your PR a **concise** yet **descriptive** title_

----

### Checklist (never delete this)

- [ ] Each method/class/object/trait should have scaladocs
- [ ] Added methods are unit tested
- [ ] Test coverage may not drop
- [ ] Documentation should be updated if required

2018-06-21 14:14 UTC, ffinfo requested changes

2018-06-21 14:14 UTC, ffinfo commented on src/main/scala/nl/biopet/utils/biowdl/references/Reference.scala
> +  def referenceGtf: Option[File] = None
This should not be part of reference, this 1 reference can have multiple annotations.
Better make a trait Annotation like this:
```scala
trait Annotation extends Reference {
  //Do things
}
```

2018-06-21 14:14 UTC, ffinfo commented on src/main/scala/nl/biopet/utils/biowdl/samples/Rna3.scala
> +                 "wgs1",
Wrong sample?

2018-06-21 14:16 UTC, DavyCats commented on src/main/scala/nl/biopet/utils/biowdl/samples/Rna3.scala
> +                 "wgs1",
oops :sweat_smile:

2018-06-22 06:16 UTC, ffinfo requested changes

2018-06-22 06:16 UTC, ffinfo commented on src/main/scala/nl/biopet/utils/biowdl/annotations/Annotation.scala
> +  def referenceGtf: Option[File] = None
No implementation needed here (so remove ' = None' ;) )

2018-06-22 06:16 UTC, ffinfo commented on src/main/scala/nl/biopet/utils/biowdl/annotations/TestAnnotation.scala
> +  override def referenceGtf: Option[File] =
After comment above, no override needed anymore

2018-06-22 08:46 UTC, ffinfo requested changes

2018-06-22 08:46 UTC, ffinfo commented on src/main/scala/nl/biopet/utils/biowdl/annotations/TestAnnotation.scala
> +trait TestAnnotation extends Annotation {
should be bound to a reference, can you add `with TestReference`?

2018-06-22 11:51 UTC, ffinfo approved these changes

2018-06-22 11:54 UTC, merged